language: node_js
node_js:
    - "0.11"
    - "0.10"
    - "0.8"
    - "0.6"
    - iojs

before_install:

after_script:
    - npm install blanket
    - npm install coveralls
    - npm install mocha-lcov-reporter
    - npm install grunt-coveralls
    - npm run coveralls
